version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1945
      MYSQL_DATABASE: testing_db
      MYSQL_USER: aether
      MYSQL_PASSWORD: 1945
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: